// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilyahgbqjdgsscjhqtwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlseWFoZ2JxamRnc3NjamhxdHdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3MDg1MjgsImV4cCI6MjA4NTI4NDUyOH0.g2IGxYmqJh6MIPD67puK-QRHtzlX0-3Cica6gY-aaiE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
